### ISSUE TITLE
Broken links from Web front end [bug]

### ISSUE THREAD

**Issue by SayBeano** [brett-lempereur/icra#1]
Clicking a link results in something similar to:

http://icreacharound.xyz/%7B%22_string%22:%22http:/edigitalsurvey.com%22,%22_parts%22:%7B%22protocol%22:%22http%22,%22username%22:null,%22password%22:null,%22hostname%22:%22edigitalsurvey.com%22,%22urn%22:null,%22port%22:null,%22path%22:null,%22query%22:null,%22fragment%22:null,%22duplicateQueryParameters%22:false,%22escapeQuerySpace%22:true%7D,%22_deferred_build%22:false%7D

Which renders a 404 page.

**Comment by brett-lempereur** [comment]
Fixed in the latest version, forgot to call uri.toString().
